name: Validate Configs

on:
  pull_request:
    branches:
      - master
    paths:
      - "*.json"
      - "!*/**/*.json"
  push:
    branches:
      - master
    paths:
      - "*.json"
      - "!*/**/*.json"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config_name:
          - "aftman.json"
          - "foreman.json"
          - "renovate.json"
          - "roblox-ts.json"
          - "rokit.json"
      fail-fast: false
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4.2.1
      - name: Cache validator dependencies.
        uses: actions/cache@v4.1.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
      - name: Validate "${{ matrix.config_name }}" config.
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.0
        with:
          config_file_path: ${{ matrix.config_name }}
