name: Validate Configs

on:
  pull_request:
    branches:
      - master
    paths:
      - ./*.json
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config_file: [aftman.json, foreman.json, renovate.json, roblox-ts.json, rokit.json]
      fail-fast: false
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4.1.7
      - name: Cache validator dependencies.
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
      - name: Validate "${{ matrix.config_file }}" config.
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
        with:
          config_file_path: ${{ matrix.config_file }}
