name: Validate Renovate Configs

on:
  pull_request:
    branches:
      - master
    paths:
      - ./*.json
  push:
    branches:
      - master
    paths:
      - ./*.json

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config_file: [aftman.json, foreman.json, renovate.json, roblox-ts.json, rokit.json]
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4.1.7
      - name: Validate "${{ matrix.config_file }}" config.
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
        with:
          config_file_path: ${{ matrix.config_file }}
