name: Validate Renovate Configs

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config_file: [renovate.json, aftman.json, foreman.json, rokit.json, roblox-ts.json]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
        with:
          config_file_path: ${{ matrix.config_file }}
